In [1]:
import os 
import numpy as np
import cv2
from glob import glob
from PIL import Image
import imutils
import gc

In [ ]:
image_overlap_train = np.load('./data_split/overlap/image_overlap_train.npy')
image_overlap_val = np.load('./data_split/overlap/image_overlap_val.npy')

f_val = open('./data_split/overlap/txt_overlap_val.txt')
txt_overlap_val = []
for line in f_val:
    line = line.strip('\n')
    txt_overlap_val.append(line)
    
f_train = open('./data_split/overlap/txt_overlap_train.txt')
txt_overlap_train = []
for line in f_train:
    line = line.strip('\n')
    txt_overlap_train.append(line)

txt_overlap_train = np.array(txt_overlap_train)
txt_overlap_val = np.array(txt_overlap_val)
# image_overlap_train = np.array(image_overlap_train)
# image_overlap_val = np.array(image_overlap_val)

print(image_overlap_train.shape)
print(image_overlap_val.shape)
print(txt_overlap_train.shape)
print(txt_overlap_val.shape)

In [ ]:
# image_overlap_val = image_overlap_val.astype('float32')
# image_overlap_val /= 255
# np.save('./data_split/overlap/image_overlap_val_normal', image_overlap_val)

In [ ]:
# image_overlap_train = image_overlap_train[:6000].astype('float32')
# image_overlap_train /= 255
# np.save('./data_split/overlap/temp/d1', image_overlap_train)

In [ ]:
# image_overlap_train = image_overlap_train[6000:12000].astype('float32')
# image_overlap_train /= 255
# np.save('./data_split/overlap/temp/d2', image_overlap_train)

In [ ]:
image_overlap_train = image_overlap_train[12000:18000].astype('float32')
image_overlap_train /= 255
np.save('./data_split/overlap/temp/d3', image_overlap_train)

In [ ]:
image_overlap_train[18000:24000].shape

In [ ]:
image_overlap_train[24000:].shape

In [ ]:
image_overlap_val = np.load('./data_split/overlap/image_overlap_val_normal.npy')

In [ ]:
import random
trainData = random.sample(range(10), 10)
trainData

In [ ]:
def getProperty(data):
    for el in data:
        if el % 2 == 0:
            yield {'Data': el, 'Parity': 'even'}
        else:
            yield {'Data': el, 'Parity': 'odd'}

In [ ]:
p = getProperty(trainData)
print(p)

In [ ]:
print(next(p))
print(next(p))
print(next(p))
print(next(p))
print(next(p))
print(next(p))
print(next(p))
print(next(p))
print(next(p))
print(next(p))

In [ ]:
for n in getProperty(trainData):
    print(n)

In [8]:
a = np.arange(105)
def batch_gen(data):  # 定义batch数据生成器
    idx = 0
    while True:
#         if idx+10>100:
#             idx=0
        start = idx
        idx += 10
        yield data[start:start+10]

In [9]:
gen = batch_gen(a)
for i in range(20):
    b = next(gen)  # 在循环中利用next()函数调用batch数据
    print(b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]
[60 61 62 63 64 65 66 67 68 69]
[70 71 72 73 74 75 76 77 78 79]
[80 81 82 83 84 85 86 87 88 89]
[90 91 92 93 94 95 96 97 98 99]
[100 101 102 103 104]
[]
[]
[]
[]
[]
[]
[]
[]
[]
